# Generated by Django 4.1.5 on 2023-01-16 12:47

import core.choices
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativo'), ('finished', 'Finalizado')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, core.choices.CourseStatusChoices),
        ),
    ]
