# Generated by Django 4.1.5 on 2023-01-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_historicalcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcourse',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
