# Generated by Django 4.1.5 on 2023-01-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_historicalcourse_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.ManyToManyField(blank=True, to='core.category'),
        ),
        migrations.DeleteModel(
            name='HistoricalCourse_categories',
        ),
    ]
